volumes:
  local_rocket_mongodb_data: {}

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:${RELEASE:-5.4.8-alpine}
    restart: on-failure
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      ADMIN_USERNAME: adminrc
      ADMIN_PASS: admin
      ADMIN_EMAIL: admin@example.com
      OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enforce_Password_Fallback: "false"
      OVERWRITE_SETTING_SMTP_Host: mailpit
      OVERWRITE_SETTING_SMTP_Port: 1025
      OVERWRITE_SETTING_From_Email: from@email.com
      OVERWRITE_SETTING_API_Enable_Rate_Limiter: "false"
      OVERWRITE_SETTING_Livechat_validate_offline_email: "false"
      OVERWRITE_SETTING_CREATE_TOKENS_FOR_USERS: "true"
      OVERWRITE_SETTING_Accounts_SystemBlockedUsernameList: administrator,system,user
      OVERWRITE_SETTING_Apps_Framework_Development_Mode: "true"
      OVERWRITE_SETTING_Prometheus_Enabled: "true"
      OVERWRITE_SETTING_Accounts_ShowFormLogin: "true"
      OVERWRITE_SETTING_Show_Setup_Wizard: "completed"
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    #ports:
    #  - host_ip: ${BIND_IP:-0.0.0.0}
    #    target: ${PORT:-3000}
    #    published: ${HOST_PORT:-3000}
    #    protocol: tcp
    #    mode: host

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-4.4}
    restart: on-failure
    volumes:
      - local_rocket_mongodb_data:/bitnami/mongodb
      #- ./mongodb_version/5.4.3:/bitnami/mongodb
      #- ./mongodb_version/5.4.1:/bitnami/mongodb
      #- ./mongodb_version/6.0.0:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
    #ports:
    #  - 27017:27017
